# Generated by Django 3.2.3 on 2022-05-24 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notfood', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='foto',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='producto',
            name='nombre',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='tipo',
            name='nombre',
            field=models.CharField(default='', max_length=40),
        ),
    ]
