# Generated by Django 3.2.3 on 2022-05-24 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notfood', '0002_auto_20220523_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(),
        ),
    ]
