# Generated by Django 3.2.3 on 2022-05-24 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notfood', '0004_auto_20220524_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='foto',
            field=models.ImageField(default='', null=True, upload_to='home'),
        ),
    ]
