# Generated by Django 3.2.3 on 2022-05-24 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notfood', '0006_alter_producto_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='foto',
            field=models.ImageField(default='', null=True, upload_to='producto'),
        ),
    ]
